server:
  port: 8080
spring:
  application:
    name: 02-Mini-Project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/mini_2
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: qjih rhek fgtv gagv
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ramesh.pmst@gmail.com
  thymeleaf:
    prefix: classpath:/templates/


app:
 messages:
  invalidLogin: Invalid Credentials
  invalidPwds: Both pwds should be same
  pwdUpdatedFailed: Pwd update failed
  regSuccess: Registration successful
  regFailed: Registration failed
